# Generated by Django 5.1.3 on 2024-12-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='employee',
            new_name='DomainName',
        ),
        migrations.RemoveField(
            model_name='react',
            name='department',
        ),
        migrations.AddField(
            model_name='react',
            name='Class',
            field=models.CharField(default='c', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='IPAddress',
            field=models.IntegerField(default='192.168.5.1'),
            preserve_default=False,
        ),
    ]
