# Generated by Django 5.1.3 on 2024-12-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_employee_react_domainname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='DomainName',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='react',
            name='IPAddress',
            field=models.CharField(max_length=35),
        ),
    ]
