# Generated by Django 5.1.3 on 2024-12-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_react_domainname_alter_react_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='IPAddress',
            field=models.GenericIPAddressField(),
        ),
    ]
