# Generated by Django 5.1.3 on 2024-12-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_react_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='react',
            name='DomainName',
        ),
        migrations.RemoveField(
            model_name='react',
            name='IPAddress',
        ),
        migrations.AddField(
            model_name='react',
            name='department',
            field=models.CharField(default='CSE', max_length=200),
        ),
        migrations.AddField(
            model_name='react',
            name='employee',
            field=models.CharField(default='ahmed', max_length=25),
        ),
    ]
