# Generated by Django 5.1.3 on 2024-12-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_react_class_remove_react_domainname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='IP',
            field=models.GenericIPAddressField(default='192.168.5.1'),
        ),
        migrations.AddField(
            model_name='react',
            name='domain',
            field=models.CharField(default='google.com', max_length=35),
        ),
    ]
