# Generated by Django 5.1.3 on 2024-12-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_react_ip_react_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='IP',
            field=models.CharField(default='192.168.5.1', max_length=35),
        ),
    ]
