# Generated by Django 5.1.3 on 2024-12-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_react_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='IP',
        ),
        migrations.RemoveField(
            model_name='react',
            name='domain',
        ),
        migrations.AlterField(
            model_name='react',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='react',
            name='employee',
            field=models.CharField(max_length=25),
        ),
    ]
